controller_manager:
  ros__parameters:
    update_rate: 250
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_gripper_controller:
      type: position_controllers/GripperActionController

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 50.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 2.0
      openarm_left_joint1: {goal: 0.05}
      openarm_left_joint2: {goal: 0.05}
      openarm_left_joint3: {goal: 0.05}
      openarm_left_joint4: {goal: 0.05}
      openarm_left_joint5: {goal: 0.05}
      openarm_left_joint6: {goal: 0.05}
      openarm_left_joint7: {goal: 0.05}

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 50.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 2.0
      openarm_right_joint1: {goal: 0.05}
      openarm_right_joint2: {goal: 0.05}
      openarm_right_joint3: {goal: 0.05}
      openarm_right_joint4: {goal: 0.05}
      openarm_right_joint5: {goal: 0.05}
      openarm_right_joint6: {goal: 0.05}
      openarm_right_joint7: {goal: 0.05}

left_gripper_controller:
  ros__parameters:
    joint: openarm_left_finger_joint1
    action_monitor_rate: 20.0
    goal_tolerance: 0.002
    max_effort: 7.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

right_gripper_controller:
  ros__parameters:
    joint: openarm_right_finger_joint1
    action_monitor_rate: 20.0
    goal_tolerance: 0.002
    max_effort: 7.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
